/* Allegro data file object indexes, produced by grabber v2.2 */
/* Datafile: c:\work\yiff\images.dat */
/* Date: Tue Jan 13 00:50:22 1998 */
/* Do not hand edit! */

#define BARK                             0        /* SAMP */
#define BLUEFOX                          1        /* BMP  */
#define FONT_001                         2        /* FONT */
#define FONT_002                         3        /* FONT */
#define MIDI_BGM                         4        /* MIDI */
#define MIDI_TIT                         5        /* MIDI */
#define MIDI_WIN                         6        /* MIDI */
#define MURP                             7        /* SAMP */
#define PALLETE_001                      8        /* PAL  */
#define POC                              9        /* SAMP */
#define REDFOX                           10       /* BMP  */
#define WALL                             11       /* BMP  */
#define WALLA                            12       /* BMP  */
#define WALLB                            13       /* BMP  */
#define WALLC                            14       /* BMP  */
#define YIFF                             15       /* SAMP */
#define Z_HELP                           16       /* BMP  */
#define Z_LOGO                           17       /* BMP  */
#define ZZ_SELECT                        18       /* MIDI */

