/* Allegro data file object indexes, produced by grabber.exe */
/* Do not hand edit! */

#define A_S1                0       /* (bmp)  */
#define A_S2                1       /* (bmp)  */
#define B_HIT               2       /* (bmp)  */
#define C_FLY               3       /* (bmp)  */
#define D_DOWN              4       /* (bmp)  */
#define D_WIN               5       /* (bmp)  */
#define E_FB1               6       /* (bmp)  */
#define F_SPIN1             7       /* (bmp)  */
#define G_SPIN2             8       /* (bmp)  */
#define H_SPIN3             9       /* (bmp)  */
#define I_UP1               10      /* (bmp)  */
#define J_UP2               11      /* (bmp)  */
