/* Allegro data file object indexes, produced by grabber.exe */
/* Do not hand edit! */

#define A_S1                0       /* (bmp)  */
#define A_S2                1       /* (bmp)  */
#define B_HIT               2       /* (bmp)  */
#define C_FLY               3       /* (bmp)  */
#define D_DOWN              4       /* (bmp)  */
#define D_WIN               5       /* (bmp)  */
#define E_FB1               6       /* (bmp)  */
#define F_FBX               7       /* (bmp)  */
#define G_LEG1              8       /* (bmp)  */
#define H_LEG2              9       /* (bmp)  */
#define I_LEG3              10      /* (bmp)  */
#define J_SPIN1             11      /* (bmp)  */
#define K_SPIN2             12      /* (bmp)  */
#define L_SPIN3             13      /* (bmp)  */
#define M_SPIN4             14      /* (bmp)  */
#define N_SPIN5             15      /* (bmp)  */
